services:
  concert-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CONCERT_ENVIRONMENT=dev
      - DB_URL=postgresql+asyncpg://postgres:example@concert-db:5432/concert
    depends_on:
      - concert-db
    pull_policy: never
    volumes:
      - ./mount:/mount

  concert-db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: concert
    ports:
      - "5432:5432"

  concert-pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@xyz.com
      - PGADMIN_DEFAULT_PASSWORD=example
    ports:
      - "8888:80"
